"""empty message

Revision ID: 2c490bf7e083
Revises: 302a875b8e1e
Create Date: 2019-03-13 00:15:55.829677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c490bf7e083'
down_revision = '302a875b8e1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kontrols', 'k_created_by')
    op.drop_column('reviews', 'review_for')
    op.drop_column('reviews', 'reviewed_by')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('reviewed_by', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.add_column('reviews', sa.Column('review_for', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.add_column('kontrols', sa.Column('k_created_by', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
