"""empty message

Revision ID: 3ea7a8ad6569
Revises: f9eec97bd994
Create Date: 2019-03-14 01:40:39.413010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ea7a8ad6569'
down_revision = 'f9eec97bd994'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'kontrols', ['k_geocord'])
    op.create_unique_constraint(None, 'kontrols', ['k_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'kontrols', type_='unique')
    op.drop_constraint(None, 'kontrols', type_='unique')
    # ### end Alembic commands ###
