"""empty message

Revision ID: 9bb03f5d1392
Revises: 822857a851a3
Create Date: 2019-03-12 23:51:28.595381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bb03f5d1392'
down_revision = '822857a851a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kontrols', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'kontrols', 'users', ['user_id'], ['u_id'])
    op.add_column('reviews', sa.Column('kontrol_id', sa.Integer(), nullable=True))
    op.add_column('reviews', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reviews', 'kontrols', ['kontrol_id'], ['id'])
    op.create_foreign_key(None, 'reviews', 'users', ['user_id'], ['u_id'])
    op.add_column('users', sa.Column('u_password', sa.String(length=15), nullable=False))
    op.drop_column('users', 'u_district')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('u_district', sa.VARCHAR(length=15), autoincrement=False, nullable=False))
    op.drop_column('users', 'u_password')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'user_id')
    op.drop_column('reviews', 'kontrol_id')
    op.drop_constraint(None, 'kontrols', type_='foreignkey')
    op.drop_column('kontrols', 'user_id')
    # ### end Alembic commands ###
