"""empty message

Revision ID: d1771e971aa6
Revises: 2c490bf7e083
Create Date: 2019-03-13 22:31:23.714055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1771e971aa6'
down_revision = '2c490bf7e083'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['u_email'])
    op.create_unique_constraint(None, 'users', ['u_telephone'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
